#!/bin/bash
## -i   = --include
## -a   = --add
## -ts  = --template-server
## -s   = --server
## -r   = --remove
## -c   = --comment
## -u   = --uncomment
## -m	= --mirror
[ "$(id -u)" != 0 ] && { echo "This script must be run as root" ; exit 1 ; }
conf_f=/etc/pacman.conf
conf_i=/etc/pacman.d/mirrorlist
check_repo_x() {
if [[ "$(sed "/^\$*\[$repo_name\]/! d" $conf_f)" ]]; then
echo -e "error: repository \e[1m$repo_name\e[0m already exists in $conf_f"; exit 4; fi
}
check_repo_c() {
if [[ "$(sed "/^.*\#.*\[$repo_name\]/! d" $conf_f)" ]]; then
echo -e "error: repository \e[1m$repo_name\e[0m commented out. Use \e[1mpacadd -u $repo_name\e[0m to uncomment"; exit 5; fi
}
check_space() {
[ -n "$(cat $conf_f | tail -n 1)" ] && echo >> $conf_f
}
check_addr() {
if [[ "$repo_url" != *:*/* ]]; then echo "error: invalid address"; exit 3; fi
}
case "$1" in
-h|--help|help)
cat <<__EOF__
pacadd v1.0.1

A simple tool for managing repositories

Usage: pacadd [options] NAME URL [options]

  -a, --add NAME URL			Adds [NAME] and Server=URL to $conf_f
  	-a URL -i			Adds Server=URL to $conf_i or <path> (if declared)
  	-a NAME -i			Adds [NAME] and Include=$conf_i or <path> (if declared) to $conf_f
  	-a NAME -s URL -i		Adds [NAME] and Include=$conf_i to $conf_f; Server=URL to $conf_i
  	-a NAME -s URL -i <path>	Adds [NAME] and Include=<path> to $conf_f;  Server=URL to <path>
	-a NAME -ts URL			Adds [NAME] and Server=URL/\$repo/os/\$arch to $conf_f
  	-a URL -ts			Adds Server=URL/\$repo/os/\$arch to $conf_i
  	-a URL -ts -i			Adds Server=URL/\$repo/os/\$arch to $conf_i or <path> (if declared)
  	-a NAME -s URL -i <path> -ts	Adds [NAME] and Include=<path> to $conf_f; Server=URL/\$repo/os/\$arch to $conf_i
  -r, --remove NAME			Removes [NAME] from $conf_f
  	-r -m URL			Removes Server=URL from $conf_i
  	-r -m URL <path>		Removes Server=URL from <path>
  -c, --comment NAME			Comment out the line of [NAME] from $conf_f
  -u, --uncomment NAME			Uncomment the line of [NAME] from $conf_f

__EOF__
exit 0 ;;
-a|--add)
if [[ "$(echo $2 | cut -c1)" == "-" || ! "$2" ]]; then
echo "error: invalid argument(s)"; exit 1; fi
if [ "$#" == 3 ]; then
		if [[ "$3" == "-ts" ]]; then
		repo_url="$2"
		check_addr
			if [ "$(echo $2 | rev | cut -c1)" == "/" ]; then
			repo_url=${2::-1}
			fi
			if [ "$(cat $conf_i | grep -x $repo_url)" ]; then echo "error: this mirror already exists in $conf_i"; exit 2
			else echo "$repo_url/\$repo/os/\$arch" >> $conf_i
			fi
		fi
	if [[ "$3" == "-i" || "$3" == "--include" ]]; then
		if [[ "$2" == *:*/* ]]; then
			if [ "$(cat $conf_i | grep -x $2)" ]; then echo "error: this mirror already exists in $conf_i"; exit 2
			else echo "$2" >> $conf_i
			fi
		else
		repo_name="$2"
		repo_url="$3"
		check_repo_x; check_repo_c
		check_space
		echo "$repo_name" >> $conf_f
		echo "Include = /etc/pacman.d/mirrorlist" >> $conf_f
		fi
	else
	repo_url="$3"
	check_addr
	if [[ "$3" == -* ]]; then
	echo -e "error: invalid argument for \e[1m$3\e[0m"; exit 1; fi
	check_repo_x; check_repo_c
	check_space
	repo_name="$2"
	echo "[$repo_name]" >> $conf_f
	echo "Server = $repo_url" >> $conf_f; fi
if [ "$#" == 4 ]; then
	if [[ "$3" == "-s" || "$3" == "--server" ]]; then
	repo_name="$2"
	repo_url="$4"
	check_addr
	check_repo_x; check_repo_c
	check_space
	echo "[$repo_name]" >> $conf_f
	echo "Server = $repo_url" >> $conf_f
	else
	if [[ "$3" == "-i" || "$3" == "--include" ]]; then
	something="$2"
	end_file="$4"
			if [[ ! -f "$end_file" ]]; then echo "error: file $end_file not exists"; exit 6; fi
		if [[ "$something" == *:*/* ]]; then
			if [ "$(cat $end_file | grep -x $something)" ]; then echo "error: this mirror already exists in $end_file"; exit 2
			else echo "$something" >> $end_file
			fi
		else
		check_repo_x; check_repo_c
		check_space
		echo "[$something]" >> $conf_f
		echo "Include = $end_file" >> $conf_f
		fi
	else
	if [[ "$3" == "-ts" || "$3" == "--template-server" ]]; then
	repo_name="$2"
	repo_url="$4"
	check_repo_x; check_repo_c
	check_space
		if [ "$(echo $4 | rev | cut -c1)" == "/" ]; then
		repo_url=${repo_url::-1}; fi
	echo "[$repo_name]" >> $conf_f
	echo "Server = $repo_url/\$repo/os/\$arch" >> $conf_f
	else
	if [[ "$3" == "-ts" || "$3" == "--template-server" ]] && [[ "$4" == "-i" || "$4" == "--include" ]]; then
	repo_url="$2"
	check_addr
			if [ "$(echo $repo_url | rev | cut -c1)" == "/" ]; then
			repo_url=${repo_url::-1}; fi
			_repo_url="$repo_url/\$repo/os/\$arch"
		if [ "$(cat $conf_i | grep -x $_repo_url)" ]; then echo "error: this mirror already exists in $conf_i"; exit 2
		else echo "$repo_url/\$repo/os/\$arch" >> $conf_i
		fi
	else
	echo "error: unknown argument(s)"; exit 1; fi; fi; fi; fi; fi
else
if [[ "$#" > 4 ]]; then
	if [[ "$3" == "-s" || "$3" == "--server" ]] && [[ "$5" == "-i" || "$5" == "--include" ]]; then
		if [ ! $6 ]; then echo "error: too few arguments: no file to include"; exit 1
		fi
	repo_name="$2"
	repo_url="$4"
	end_file="$6"
			if [[ ! -f "$end_file" ]]; then echo "error: file $end_file not exists"; exit 6; fi
	check_addr
			if [ "$(cat $end_file | grep -x $repo_url)" ]; then echo "error: this mirror already exists in $end_file"; exit 2; fi
	check_repo_x; check_repo_c
	check_space
	echo "[$repo_name]" >> $conf_f
	echo "Server = $repo_name" >> $end_file
	echo "Include = $end_file" >> $conf_f
	else
	if [[ "$3" == "-s" || "$3" == "--server" ]] && [[ "$5" == "-i" || "$5" == "--include" ]] && [[ "$7" == "-ts" || "$7" == "--template-server" ]]; then	
	repo_name="$2"
	_repo_url="$4"
			if [ "$(echo $_repo_url | rev | cut -c1)" == "/" ]; then
			_repo_url=${_repo_url::-1}; fi
			repo_url="$_repo_url/\$repo/os/\$arch"
	end_file="$6"
			if [[ ! -f "$end_file" ]]; then echo "error: file $end_file not exists"; exit 6; fi
	check_addr
			if [ "$(cat $end_file | grep -x $repo_url)" ]; then echo "error: this mirror already exists in $end_file"; exit 2; fi
	check_repo_x; check_repo_c
	check_space
	echo "[$repo_name]" >> $conf_f
	echo "Server = $repo_url" >> $end_file
	echo "Include = $end_file" >> $conf_f
else
echo "error: unknown argument(s)"; exit 1; fi; fi; fi; fi
;;
-r|--remove)
if [[ ! "$2" ]]; then
echo "error: invalid argument(s)"; exit 1; fi
	if [[ "$2" != "-m" || "$2" != "--mirror" ]]; then
	repo_name="$2"
		if ! [[ "$(sed "/.*\[$repo_name\]/! d" $conf_f)" ]]; then
			echo "error: repository $repo_name not found in $conf_f"; exit 7
		fi
			if [[ "$(sed "/^\#\[$repo_name\]/! d" $conf_f)" ]]; then
			repo_commented=1
			else
			repo_commented=0
			fi
	if [ "$repo_commented" == 1 ]; then
	sed "/^.*\#.*\[$repo_name\]/,/^ *$/d" -i $conf_f; else
	sed "/^\$*\[$repo_name\]/,/^ *$/d" -i $conf_f
	fi
	else
	if [[ ! "$3" ]]; then
	echo "error: too few argument(s)"; exit 1; fi
		if [ "$4" ]; then
		if ! [ -f "$4" ]; then echo "error: file $4 not exists"; exit 6; fi
		repo_url="$3"
		end_file="$4"
		sed "/.*${repo_url}/ d" -i $end_file
		else
		repo_url="$3"
		sed "/.*${repo_url}/ d" -i $conf_i
		fi
	fi
;;
-u|--uncomment)
if [[ ! "$2" ]]; then
echo "error: invalid argument(s)"; exit 1; fi
repo_name="$2"
	if [ -z "$(sed "/^.*\#.*\[$repo_name\]/! d" $conf_f)" ]; then
	echo "error: commented out repository $repo_name not found in $conf_f"; exit 7; fi
if [[ -n $(sed -n "/^.*\#.*\[$repo_name\]/,/^ *$/p" $conf_f | tail -n 1) ]]; then
lines="$(sed -n "/^.*\#.*\[$repo_name\]/,/^ *$/p" $conf_f | sed '1 d' | wc -l)"; else
lines="$(sed -n "/^.*\#.*\[$repo_name\]/,/^ *$/p" $conf_f | sed '1 d;$ d' | wc -l)"; fi
sed "/^\$*.*\#.*\[$repo_name\]/,+$lines s/# *//" -i $conf_f
;;
-c|--comment)
if [[ ! "$2" ]]; then
echo "error: invalid argument(s)"; exit 1; fi
repo_name="$2"
	if [ -z "$(sed "/^\$*\[$repo_name\]/! d" $conf_f)" ]; then
	echo "error: uncommented repository $repo_name not found in $conf_f"; exit 7; fi
if [[ -n $(sed -n "/^\$*\[$repo_name\]/,/^ *$/p" $conf_f | tail -n 1) ]]; then
lines="$(sed -n "/^\$*\[$repo_name\]/,/^ *$/p" $conf_f | sed '1 d' | wc -l)"; else
lines="$(sed -n "/^.*\#.*\[$repo_name\]/,/^ *$/p" $conf_f | sed '1 d;$ d' | wc -l)"; fi
sed "/^\$*\[$repo_name\]/,+$lines s/^/#/" -i $conf_f
;;
*)
echo "error: unknown argemunt"; exit 1
;;
esac
